version: '3.8'

services:
  backend:
    build: ./
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - MAIL_DOMAIN=${MAIL_DOMAIN}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - SMTP_PORT=${SMTP_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - database
    networks:
      - dawachat_net

  frontend:
    build: ../dawachat_frontend/
    expose:
      - "80"
    depends_on:
      - backend
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      
    networks:
      - dawachat_net

  database:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - dawachat_net
  
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - dawachat_net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    command: certonly --webroot -w /var/www/certbot --email info@advernet.africa --agree-tos --no-eff-email -d dawachat.advernet.africa

    networks:
      - dawachat_net

volumes:
  db_data:

networks:
  dawachat_net:
    driver: bridge
