version: '3.8'

services:
  backend:
    build: ./
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/dawachat
    depends_on:
      - database

  frontend:
    build: ../../dawachat_frontend/
    ports:
      - "3000:80" 
    depends_on:
      - backend

  database:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dawachat
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
